### ISSUE TITLE
Problem with rendering circles in collections

### ISSUE THREAD

**Issue by mirtoto** [morehawes/waymark#1]
In changelog there is information that "Editor circle bug fix" in v0.9.15. It seems that it was only partially fixed - when maps in collection contain circles there are still not showing. 

Test page with sample collection ("Collection 1") and three maps ("Map 1", "Map 2", "Map 3") in this collections: [http://test.pix.nsfera.pl/waymark/](http://test.pix.nsfera.pl/waymark/).

**Comment by morehawes** [comment]
Hi @mirtoto,

Thanks for bringing this to my attention, I am seeing this too. I will take a proper look when I have more time.

Cheers,

Joe

**Comment by morehawes** [comment]
Hi @mirtoto,

Please let me know if [this](https://github.com/morehawes/waymark/commit/abf2a04b484e233b828c14403b286f122b2feba2) resolved the issue for you.

Joe

**Comment by mirtoto** [comment]
Hi Joe,

Yes. After applying your update to my test site the sample collection looks as expected. Thanks.

By the way - thanks also for whole plugin. It works really amazing.

I have one more problem regarding to collections and will try to describe it in separate issue.

Mirek

**Comment by morehawes** [comment]
Hi Mirek,

Good news :) Glad to hear you like the plugin, [reviews](https://wordpress.org/support/plugin/waymark/reviews/) are always appreciated if you haven't already.

Joe
