### ISSUE TITLE
Add PHP8+ support

### ISSUE THREAD

**Issue by huubl** [morehawes/waymark#14]
Hi,

Right now the plugin doesn't seem to support PHP8+.

**Comment by morehawes** [comment]
Hi @huubl,

Could you provide some more details? I am running Waymark on multiple PHP 8 environments and am not currently aware of any issues.

Cheers,

Joe

**Comment by huubl** [comment]
Hi @morehawes,

Sorry for the delay! The problems turned out not to be caused by this plugin.

But I do get deprecation warnings: `Optional parameter is provided before required` (https://php.watch/versions/8.0/deprecate-required-param-after-optional)

For example here:
https://github.com/morehawes/waymark/blob/ca0e135d506a51cf2b525b080eace36e9e9383cb/inc/Waymark_Config.php#L199

**Comment by morehawes** [comment]
Thanks for the update, I will keep an eye out for the deprecation notices. 


Joe
