### ISSUE TITLE
Cannot get to load the elevation profile

### ISSUE THREAD

**Issue by ekhakbaz** [morehawes/waymark#15]
Hey, Thanks for this awesome plugin!
I cannot enable the elevation profile, even by setting the parameter on the shortcode. Is there an instruction on adding lines that pull the elevation data?

**Comment by morehawes** [comment]
Hi @ekhakbaz, thanks for reaching out :)

>Is there an instruction on adding lines that pull the elevation data?

Please note that Waymark does not "look up" elevation data, it simply displays it if it is available in the file uploaded.

There are free tools available for doing this, I can recommend [GPS Visualizer](https://www.gpsvisualizer.com/elevation) for GPX files.

This is a feature I would like to include in Waymark one day, but the list is long!

Please do let me know if this did not solve your issue.

Cheers,

Joe
