### ISSUE TITLE
Full screen / jump to top of the page 

### ISSUE THREAD

**Issue by phrizm** [morehawes/waymark#16]
Hello Joe. It might be very personal problem but when I open full screen map it's jumps to the top of my page. It's could be my theme problem (bootscore), but I had similar problem with glightbox interaction. One line of code in case of glightbox helped a lot (css).
 https://www.northwestalps.com/2020/03/08/2020-oman-and-emirates/

This one is a page. Try to go in full screen. I will found a solution in the next days and tell you how to fix it but I'm sure you know how to do it. Once it done maybe a little blank field with some custom class can fix this issue to multiple themes.

Atm thanks.

**Comment by morehawes** [comment]
Hi @phrizm,

Thanks for letting me know about this, however it works as expected for me so I'm not really understanding what the issue is.

If you believe this to be a bug with Waymark could you set up a simple demo page showing the unexpected behavior?

Thanks again!

Joe
