### ISSUE TITLE
Elevation stopped working

### ISSUE THREAD

**Issue by davinian** [morehawes/waymark#19]
Hi, I have noticed that my maps no longer show the Elevation - not sure when this stopped, possibly after the last update but could have been before that.

I have Elevation Profile set to Hide Everywhere in the settings and only use it in shortcodes so wonder if something has changed?

To confirm, all my maps have embedded elevation data and used to work.

Kind regards,
David

**Comment by davinian** [comment]
Apologies — just realised my cookie policy was blocking unpkg.com 🙄

**Comment by morehawes** [comment]
Hi @davinian,

Im glad you got it sorted :)

Cheers,

Joe
