### ISSUE TITLE
Website Fails to Load When Adding Multiple Cards to a Collection Using a Shortcode

### ISSUE THREAD

**Issue by davidmederake** [morehawes/waymark#20]
Hello there,

I am experiencing an issue with your application that seems to be caused by a specific sequence of actions.

Steps to reproduce:

Add more than one card to a collection.
Load the page that contains the shortcode for the said collection.
Expected result:

The page loads correctly, displaying all the cards within the collection.

Actual result:

The entire webpage fails to load and remains blank (white screen). This behavior only occurs when multiple cards are added to a collection and that collection is called with a shortcode on a page.

You can see here 

https://vantusky.info/bugreport/

There are only the Shortcode [Waymark collection_id="13"] with these two card 
https://vantusky.info/reiseverlauf-und-highlights-von-unserer-vanlife-tour/

**Comment by morehawes** [comment]
Hi @davidmederake,

Thanks for reaching out and sorry to hear about this issue. I have not seen this before and am unable to replicate.

It is weird that the Shortcode would stop the entire page from loading. Just to confirm - when you say "card", do you mean "Map"?

Are you seeing anything in your PHP "error_log" file?

Cheers,

Joe

**Comment by davidmederake** [comment]
Hi 

sorry my English is bad. 
After i activate Error Log the following Error comes:

[26-Jun-2023 06:48:07 UTC] PHP Fatal error:  json_decode(): Cannot use output buffering in output buffering display handlers in /www/htdocs/w01d70af/vantusky.info/wp-content/plugins/real-cookie-banner-pro/vendor/devowl-wp/fast-html-tag/src/Utils.php on line 49
						

Its my Cookie Consent Tool 

Yes with ”card” i mean the „map"

**Comment by davidmederake** [comment]
Thanks, with the help of the error log I found the problem and after deactivating the cookie tool it turned out I had to raise the memory limit in wordpress. Now everything works as it should. 


Thanks a lot @morehawes

**Comment by morehawes** [comment]
Hi @davidmederake,

I'm glad you got it sorted. Please remember to Star this repository! :0)

Cheers,

Joe
