### ISSUE TITLE
Feature Request: Ability to change elevation units on a per map basis

### ISSUE THREAD

**Issue by randombuffalo** [morehawes/waymark#22]
Hi there! We love the plugin and are using it for an upcoming website launch.  Instead of just a global option for units, it would be great if we could change the unit type on the elevation profile on a per map basis.  Either by adding a shortcode parameter or by setting the option on the map editor. This would allow us to show maps/routes in the same unit as the region in the map uses.

Maybe this is already a thing but I couldn't find documentation to support it. Thanks for your time!

**Comment by morehawes** [comment]
Hi @randombuffalo,

Thanks for your suggestion. I have just added the ability to specify the elevation units (metric or imperial) through the Shortcode in the latest release (v0.9.28.5). You can do so like this:

`[Waymark map_id="1234" elevation_units="metric"]`

Please let me know if you experience any issues with this.

Cheers,
Joe

**Comment by randombuffalo** [comment]
Thanks @morehawes!  really appreciate you being open to the request.  I'll test it out and let you know if we have any feedback!

**Comment by morehawes** [comment]
You’re welcome. Please star the GitHub repo/leave a WordPress review if you like the plugin as that really helps :)

Cheers,

Joe
