### ISSUE TITLE
map_zoom option in shortcode doesn't work

### ISSUE THREAD

**Issue by killianweid** [morehawes/Waymark#25]
Hello,
I found one particular bug linked to map_zoom option in shortcode.
This option becomes useless because of "setup_hidden_checker" function in Waymark_Map_Viewer.js (call during the init) which call the reset_data_view function which also call Waymark.map.fitBounds() and so change the zoom of the map.
I don't know if it's the desired behavior but this prevents you from using the option map_zoom in shortcodes..

Best regards,
Killian

**Comment by morehawes** [comment]
Hi @killianweid,

Thanks for letting me know about this and for drilling down into the cause, that helped save a lot of time 👍 

I have just released v0.9.29.2 which should resolve this.

Please do let me know if you encounter any more issues.

Cheers,
Joe
