### ISSUE TITLE
Error on adding new setting

### ISSUE THREAD

**Issue by killianweid** [morehawes/Waymark#26]
Hello, when I try to add new setting on the Settings page of the plugin (https://mywebsite.com/wp-admin/edit.php?post_type=waymark_map&page=waymark-settings) there is an error. According to WordPress the error is coming from the line 421 from the inc/Helpers/Waymark_Input.php file.
The error message is : "syntax error, unexpected ";"

Killian

**Comment by morehawes** [comment]
Hi @killianweid,

Thanks for reaching out. I am not seeing this, perhaps a file got corrupted on your end? You might want to try removing the plugin and re-installing it.

Please do let me know if you continue to have issues.

Cheers,

Joe
