### ISSUE TITLE
Incorrect download content

### ISSUE THREAD

**Issue by shenki** [morehawes/waymark#3]
Hello! I am using your plugin for a running community website and it's great.

We've got a setup where we have three different maps on the one page, and they display fine. However, when using the GPX download function the file contains the incorrect content. You can see here:

https://trailrunningsa.com/mt-misery-2021/#Short

Details -> Download

Is this a bug in the plugin, or are we using it incorrectly?

**Comment by morehawes** [comment]
Hi @shenki,

Thanks for reaching out. I'm glad you like the plugin, this kind of use-case was exactly what I had in mind when creating Waymark :) I have lots more features to come!

I can see this on your site too: when downloading using the Shortcode Header each file contains the "Long" Map data. So this does appear to be a bug.

I am a little pressed for time at the moment, but I will be sure to spend some time on this in the next week or two. I will let you know if I have trouble replicating this on my end.

When Exporting from the Map Details page (i.e. clicking "Details" > "More Details") things appear to be working correctly. As a temporary work-around you could hide the Export option from the Shortcode with this CSS:

`.waymark-shortcode .waymark-header .waymark-meta-export_data {
  display: none;
}`

Thanks again,

Joe

**Comment by morehawes** [comment]
Hi @shenki,

I have created a fix for this, available in [this branch](https://github.com/morehawes/waymark/tree/fix-multi_export). Please feel free to download this version and let me know if the Export feature is now working as expected.

Please note you may need to clear your browser cache (of Waymark JavaScript) to see the change.

Cheers,

Joe

**Comment by morehawes** [comment]
This fix is included in the [latest release](https://github.com/morehawes/waymark/commit/b8f4935d21eadcca906708a0283c3826ffa64aaa). Marking as closed, thanks again for bringing this to my attention.

Joe

**Comment by shenki** [comment]
Thanks for your help @morehawes

I've updated to the new version and it's working as we would expect.
