### ISSUE TITLE
Track direction indicator

### ISSUE THREAD

**Issue by shenki** [morehawes/waymark#4]
It would be great to be able to style the track to indicate direction, for the case where it is ambiguous which way an overlapping track exits a junction.

**Comment by morehawes** [comment]
Agreed! I have added it to my to-do list.

Joe

**Comment by morehawes** [comment]
Hi @shenki,

Sorry it took so long, but I have just added this feature to the latest release (v0.9.28).

To add a direction, click on a Line while editing a Map and select from the direction dropdown.

Please let me know if you encounter any issues.

Cheers,

Joe
