### ISSUE TITLE
Feature: options page to override post type/taxonomy settings like slug

### ISSUE THREAD

**Issue by huubl** [morehawes/waymark#6]
Hi,

What about an option or filter to set custom slugs (and maybe labels) for the `waymark_map` post type and `waymark_collection` taxonomy?

**Comment by morehawes** [comment]
Hi @huubl,

Thanks for reaching out. Unless I misunderstand, this is already available for [Maps](https://www.waymark.dev/wp-content/uploads/2021/11/Screen-Shot-2021-11-09-at-7.23.23-AM.png) and [Collections](https://www.waymark.dev/wp-content/uploads/2021/11/Screen-Shot-2021-11-09-at-7.25.11-AM.png).

Please do let me know if this is not the case for you.

Cheers,

Joe

**Comment by huubl** [comment]
Hi,

I'm talking about this part:
![image](https://user-images.githubusercontent.com/50170696/142416507-5833d222-36fc-4d1a-ae2f-014ea00fbef5.png)

What I actually meant is to have control over the setting, e.g. using a custom `slug`, `labels` and set `archive` to true.

https://github.com/morehawes/waymark/blob/bef8c7a9d0e177b13bfaf73d8213e5f4a3abaacd/inc/Waymark_Types.php#L7-L54

**Comment by morehawes** [comment]
Nice idea! I had considered this at the time of hard coding "map" and "collection" into the rewrites, I figured someone would ask for it at some point.

I will look into adding these as Settings.

Cheers,

Joe
